WITH CTE_UNION as (
SELECT 
acc.id,
acc.account_uuid,
acc.customer_code,
acc.advertiser_name,
acc.provider_id,
NULL as tracking_uuid,
acc.advertiser_address_id,
NULL as idDniGroup,
NULL as publisher_group_id,
NULL as WebPublisher_idWebPublisher_FK,
NULL as Campaign_idCampaign_Master_FK,
NULL as WebPublisherCampaign_idWebPublisherCampaign_FK,
acc.master_advertiser_id,
'NULL' as tracking_javascript,
'NULL' as country,
'NULL' as status,
DATE(acc.created_on) as created_on,
acc.updated_on,
acc.datastream_metadata.uuid,
acc.datastream_metadata.source_timestamp,
NULL as original_number,
NULL as target_number,
NULL AS tracking_number,
NULL AS number_type,
NULL AS initial_number_type,
NULL AS number_match,
NULL AS campaign_type,
NULL AS referrer_type,
NULL AS call_recording,
NULL AS whisper,
NULL AS site_id,
NULL AS location_id,
NULL AS location_uri,
NULL AS error_messages,
NULL AS is_legacy,
NULL AS is_match,
NULL AS remarks,
NULL AS auto_delete_status,
NULL AS call_verify,
NULL AS call_verify_notification_text,
NULL AS advertiser_business_name,
NULL AS source,
NULL AS name,
NULL AS description,
NULL AS web_publisher_id
from `localiq-dms-analytics-v2-prod.rl_cts.Account` acc

UNION ALL

SELECT
NULL as id,
'NULL' as account_uuid,
'NULL' as customer_code,
'NULL' as advertiser_name,
NULL as provider_id,
NULL tracking_uuid,
NULL as advertiser_address_id,
dg.idDniGroup,
dg.publisher_group_id,
dg.WebPublisher_idWebPublisher_FK,
dg.Campaign_idCampaign_Master_FK,
dg.WebPublisherCampaign_idWebPublisherCampaign_FK,
dg.master_advertiser_id,
dg.tracking_javascript,
dg.country,
dg.status,
DATE(dg.created_time) as created_on,
NULL as updated_on,
datastream_metadata.uuid,
datastream_metadata.source_timestamp,
NULL as original_number,
NULL as target_number,
NULL AS tracking_number,
NULL AS number_type,
NULL AS initial_number_type,
NULL AS number_match,
NULL AS campaign_type,
NULL AS referrer_type,
NULL AS call_recording,
NULL AS whisper,
NULL AS site_id,
NULL AS location_id,
NULL AS location_uri,
NULL AS error_messages,
NULL AS is_legacy,
NULL AS is_match,
NULL AS remarks,
NULL AS auto_delete_status,
NULL AS call_verify,
NULL AS call_verify_notification_text,
NULL AS advertiser_business_name,
NULL AS source,
NULL AS name,
NULL AS description,
NULL AS web_publisher_id
from `localiq-dms-analytics-v2-prod.rl_cts.DniGroup` dg

UNION ALL

SELECT
tn.id,
CAST(tn.account_id AS STRING) as account_uuid,
'NULL' AS customer_code,
'NULL' as advertiser_name,
NULL AS provider_id,
tn.tracking_uuid,
tn.advertiser_address_id,
NULL as idDniGroup,
NULL as publisher_group_id,
NULL as WebPublisher_idWebPublisher_FK,
tn.master_campaign_id as Campaign_idCampaign_Master_FK,
tn.webpublisher_campaign_id as WebPublisherCampaign_idWebPublisherCampaign_FK,
tn.master_advertiser_id,
NULL as tracking_javascript,
tn.country,
CAST(tn.status_id as string) as status,
DATE(tn.created_on) as created_on,
DATE(tn.updated_on) as updated_on,
datastream_metadata.uuid,
datastream_metadata.source_timestamp,
tn.original_number,
NULL as target_number,
NULL AS tracking_number,
NULL AS number_type,
NULL AS initial_number_type,
NULL AS number_match,
NULL AS campaign_type,
NULL AS referrer_type,
NULL AS call_recording,
NULL AS whisper,
NULL AS site_id,
NULL AS location_id,
NULL AS location_uri,
NULL AS error_messages,
NULL AS is_legacy,
NULL AS is_match,
NULL AS remarks,
NULL AS auto_delete_status,
NULL AS call_verify,
NULL AS call_verify_notification_text,
NULL AS advertiser_business_name,
NULL AS source,
NULL AS name,
NULL AS description,
NULL AS web_publisher_id
from `localiq-dms-analytics-v2-prod.rl_cts.TrackingNumber` tn

UNION ALL

SELECT 
tp.id,
'NULL' as account_uuid,
'NULL' as customer_code,
'NULL' as advertiser_name,
NUll as provider_id,
NULL as tracking_uuid,
NULL as advertiser_address_id,
NULL as idDniGroup,
NULL as publisher_group_id,
NULL as WebPublisher_idWebPublisher_FK,
NULL as Campaign_idCampaign_Master_FK,
NULL as WebPublisherCampaign_idWebPublisherCampaign_FK,
NULL as master_advertiser_id,
NULL as tracking_javascript,
NULL as country,
NULL as status,
DATE(tp.created_on) as created_on,
DATE(tp.updated_on) as updated_on,
datastream_metadata.uuid,
datastream_metadata.source_timestamp,
NULL as original_number,
NULL as target_number,
NULL AS tracking_number,
NULL AS number_type,
NULL AS initial_number_type,
NULL AS number_match,
NULL AS campaign_type,
NULL AS referrer_type,
NULL AS call_recording,
NULL AS whisper,
NULL AS site_id,
NULL AS location_id,
NULL AS location_uri,
NULL AS error_messages,
NULL AS is_legacy,
NULL AS is_match,
NULL AS remarks,
NULL AS auto_delete_status,
NULL AS call_verify,
NULL AS call_verify_notification_text,
NULL AS advertiser_business_name,
NULL AS source,
NULL AS name,
NULL AS description,
tp.webpublisher_id as web_publisher_id
from `localiq-dms-analytics-v2-prod.rl_cts.TrackingProvider` tp 

UNION ALL

SELECT
id,
'NULL' as account_uuid,
'NULL' as customer_code,
'NULL' as advertiser_name,
NULL as provider_id,
NULL tracking_uuid,
NULL as advertiser_address_id,
NULL as idDniGroup,
NULL as publisher_group_id,
NULL as WebPublisher_idWebPublisher_FK,
NULL as Campaign_idCampaign_Master_FK,
NULL as WebPublisherCampaign_idWebPublisherCampaign_FK,
NULL as master_advertiser_id,
NULL as tracking_javascript,
NULL as country,
NULL as status,
DATE(ts.created_on) as created_on,
DATE(ts.updated_on) as updated_on,
datastream_metadata.uuid,
datastream_metadata.source_timestamp,
NULL as original_number,
NULL as target_number,
NULL AS tracking_number,
NULL AS number_type,
NULL AS initial_number_type,
NULL AS number_match,
NULL AS campaign_type,
NULL AS referrer_type,
NULL AS call_recording,
NULL AS whisper,
NULL AS site_id,
NULL AS location_id,
NULL AS location_uri,
NULL AS error_messages,
NULL AS is_legacy,
NULL AS is_match,
NULL AS remarks,
NULL AS auto_delete_status,
NULL AS call_verify,
NULL AS call_verify_notification_text,
NULL AS advertiser_business_name,
NULL AS source,
ts.name as name,
ts.description as description,
NULL as web_publisher_id
from `localiq-dms-analytics-v2-prod.rl_cts.TrackingStatus` ts
),
not_found as (
SELECT 
cast(fdcr.CallSid as string) AS call_id,
NULL AS call_type,
fdcr.Disposition AS call_status,
fdcr.From AS caller_number,
CAST(
    CASE 
      when fdcr.To is not null then REGEXP_REPLACE(cast(`To` as string), r'^1|^55|^81|^44|^52|^61|^64|^65|^31|^49|^43|^32|^353|^56|^54','') 
    END AS STRING
) AS dialed_number,

CAST(
    CASE 
      when fdcr.Endpoint is not null then REGEXP_REPLACE(cast(`Endpoint` as string), r'^1|^55|^81|^44|^52|^61|^64|^65|^31|^49|^43|^32|^353|^56|^54','') 
    END AS STRING
) AS target_number,
NULL as caller_name,
fdcr.From_City as caller_city,
fdcr.From_Region as caller_state,
NULL as caller_zip,
fdcr.From_CountryCode as caller_country,
NULL as caller_address,
TIMESTAMP(fdcr.Date_Start) AS start_time,
fdcr.duration AS duration,
CURRENT_TIME() AS created_on,
CURRENT_TIME() AS updated_on,
fdcr.Recording_Uri as mailbox_url,
NULL AS call_page_info,
NULL as call_page_geo_keyword_id,
NULL as attribution_source,
fdcr.Attribution_Medium as wpc_id,
fdcr.Attribution_Campaign as MCID,
CASE 
    WHEN REGEXP_CONTAINS(attribution_source, r'^[A-Z]{3}_[0-9]+$') THEN 
      SPLIT(attribution_source, '_')[SAFE_OFFSET(1)]
END AS MAID,
dg.publisher_group_id as publisher_group_id
FROM `dms-data-lake-development.fonedynamics.calls_report` fdcr
LEFT JOIN
 `localiq-dms-analytics-v2-prod.rl_cts.DniGroup` dg
ON CAST(REGEXP_REPLACE(fdcr.GroupName , '[^0-9]', '') as BIGINT) = dg.publisher_group_id
WHERE DATE(fdcr.start_time) > '2020-01-01'
and (dg.idDniGroup is null or fdcr.GroupName is null)
)
SELECT 
n.call_id,
n.call_type,
n.call_status,
n.caller_number,
n.dialed_number,
n.target_number,
n.caller_name,
n.caller_city,
n.caller_state,
n.caller_zip,
n.caller_country,
n.caller_address,
n.start_time,
n.duration,
n.created_on,
n.updated_on,
n.mailbox_url,
n.call_page_info,
n.call_page_geo_keyword_id,
n.attribution_source,
n.wpc_id,
n.MCID,
n.MAID,
n.publisher_group_id,
1023 as web_publisher_id
FROM not_found n
LEFT JOIN CTE_UNION cu
ON n.target_number = CAST(cu.publisher_group_id AS STRING)
WHERE cu.publisher_group_id IS NULL;
